---
apiVersion: v1
kind: Service
metadata:
  name: pod-reloader-webhook
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 2443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pod-reloader-webhook
  namespace: default
subsets:
- addresses:
  - ip: ${HOST_IP}
  ports:
  - port: 2443
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pod-reloader-webhook
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pod-reloader-webhook
  namespace: default
spec:
  dnsNames:
  - pod-reloader-webhook
  - pod-reloader-webhook.default
  - pod-reloader-webhook.default.svc
  - pod-reloader-webhook.default.svc.cluster.local
  issuerRef:
    name: pod-reloader-webhook
  secretName: pod-reloader-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-reloader-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/pod-reloader-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: pod-reloader-webhook
      namespace: default 
      path: /mutate
      port: 443
  name: mutate.generic
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    - statefulsets
    - daemonsets
    scope: Namespaced
  matchPolicy: Exact
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
  reinvocationPolicy: Never
